// sema-core — the rkyv contract types for askic↔semac.
//
// Parse tree domains generated by corec from core/*.aski.
// Name wrappers and Span defined here directly (bootstrap).
//
// Run `corec core generated/sema_core.rs` to regenerate.

use rkyv::{Archive, Serialize, Deserialize};

// ── Typed name wrappers ──────────────────────────────────
// Each wraps a String. In true sema these become domain
// variant indices with no strings. For the bootstrap: String.

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct VariantName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct FieldName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct MethodName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TraitName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeParamName(pub String);

// ── Source position ──────────────────────────────────────

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}

// ── Generated parse tree domains ─────────────────────────

include!("../generated/sema_core.rs");
