// sema-core — the rkyv contract types for veric→semac.
//
// Verified program types generated by corec from core/*.aski.
// veric serializes Program, semac/domainc/rsc/askid deserialize.
//
// Run `corec core generated/sema_core.rs` to regenerate.

// ── Generated verified program types ────────────────────────

include!("../generated/sema_core.rs");
